#!/bin/bash

echo "Content-type:text/html\r\n\r\n"
echo "<!DOCTYPE html>"
echo "<html lang="en">"
echo "<head>"
echo "<meta charset="utf-8" />"
echo "<title>HTML5</title>"
echo "</head>"
echo "<body>"
echo "CGI WORK! <br>"
echo "</body>"
echo "</html>"
